name: CheckOrg

on:
  issue_comment:
    types: [created]

jobs:
  snapshot:
    name: Check org
    if:
      ${{ github.event.issue.pull_request && github.event.comment.body ==
      '/check-org' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create and publish snapshot release
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const results = await github.rest.orgs.checkMembershipForUser({
              'aaronccasanova',
              'aaronccasanova',
            })
            console.log('results: ', results)
