name: CI

on:
  pull_request: ~
  push:
    branches: [main, changeset-release/*]
  workflow_dispatch:

jobs:
  node-tests:
    runs-on: ubuntu-latest
    name: 'Test'
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
        name: Checkout


      - name: 📦 Install dependencies
        run: echo "Hello I am a silly CI test"


