name: Snapit

on:
  issue_comment:
    types: [created]

jobs:
  snapshot:
    name: Snapshot Release
    if:
      ${{ github.event.issue.pull_request && github.event.comment.body ==
      '/snapit' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add initial reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: context.payload.comment.id
          reactions: eyes

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Dump github.event.issue
        run: echo '${{ toJSON(github.event.issue) }}'

      - name: Dump context.payload.comment
        run: echo '${{ toJSON(context.payload.comment) }}'

      - name: Add final reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: context.payload.comment.id
          reactions: rocket
