name: Snapit

on:
  issue_comment:
    types: [created]

jobs:
  snapshot:
    name: Snapshot Release
    if:
      ${{ github.event.issue.pull_request && github.event.comment.body ==
      '/snapit' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add initial reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes

      - name: Log things
        run: |
          echo 'ref ${{ github.ref }}'
          echo 'head_ref ${{ github.head_ref }}'
          echo 'ref_name ${{ github.ref_name }}'
          echo 'action_ref ${{ github.action_ref }}'
          echo 'base_ref ${{ github.base_ref }}'

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      - name: Create snapshot release
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version-packages -- --snapshot snapshot-release
          publish: echo nope
        # publish: npm run release -- --no-git-tags --snapshot
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add final reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: rocket
