name: Snapit

on:
  issue_comment:
    types: [created]

jobs:
  snapshot:
    name: Snapshot Release
    if:
      ${{ github.event.issue.pull_request && github.event.comment.body ==
      '/snapit' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add initial reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes

      - name: Checkout default branch
        uses: actions/checkout@v2

      - name: Checkout pull request branch
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Create snapshot release
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version-packages -- --snapshot snapshot-release
          publish: echo nope
        # publish: npm run release -- --no-git-tags --snapshot
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add final reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: rocket
