name: Snapit

on:
  issue_comment:
    types: [created]

jobs:
  snapshot:
    name: Snapshot Release
    if:
      ${{ github.event.issue.pull_request && github.event.comment.body ==
      '/snapit' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add initial reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes

      - name: Checkout default branch
        uses: actions/checkout@v2

      - name: Checkout pull request branch
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Create an .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create snapshot versions
        run: |
          npm run version-packages -- --snapshot snapshot-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish snapshots
        id: publish_snapshots
        run: |
          # Runs the snapshot release script and redirects to stdout and variable
          # https://unix.stackexchange.com/a/526905
          exec 5>&1
          publish_snapshots_stdout=$(
            npm run release -- --no-git-tags --snapshot |
            tee /dev/fd/5
          )
          echo "::set-output name=stdout::$publish_snapshots_stdout"
          
      - name: Log publish_snapshots output
        run: echo '${{ steps.publish_snapshots.outputs.stdout }}'

      - name: Add final reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: rocket
